# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-16 09:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='slug',
            field=models.SlugField(max_length=500, null=True),
        ),
    ]
